server:
  port: 80
  servlet:
    context-path: /

spring:
  http:
    encoding:
      force: true   #使用阿里的fastJson时必须配置此项，不然会乱码
  cache:
      type: ehcache
      ehcache:
        config: classpath:config/ehcache.xml
  redis:
    database: 0   # Redis数据库索引
    host: 47.95.238.73
    port: 6379
    password: motherfucker
    timeout: 180000   # 连接超时时间（毫秒）
    max-active: 10   # 连接池最大连接数（使用负值表示没有限制）
    max-wait: 15000   # 获取连接的最大等待时间（使用负值表示没有限制）（毫秒）
    max-idle: 8   # 连接池中的最大空闲连接数
    min-idle: 0   # 连接池中的最小空闲连接数
    cache-name: first_cache
    expiration-time: 600   # 缓存失效时间（秒）

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:config/logback.xml
  level:
    com.aidilude.***.mapper: debug  # 添加sql日志输出